// <auto-generated />
using System;
using KushBot.Resources.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KushBot.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20240915220817_UserEvents")]
    partial class UserEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("KushBot.DataClasses.ConsumableBuff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Potency")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConsumableBuffs");
                });

            modelBuilder.Entity("KushBot.DataClasses.Infection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BapsDrained")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KillAttemptDate")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserInfections");
                });

            modelBuilder.Entity("KushBot.DataClasses.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirDropFlat")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AirDropPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("BossDmg")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestBapsFlat")
                        .HasColumnType("INTEGER");

                    b.Property<double>("QuestBapsPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("QuestSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("KushBot.DataClasses.ItemPetConn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LvlBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemPetBonus");
                });

            modelBuilder.Entity("KushBot.DataClasses.NyaClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Keys")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("NyaClaims");
                });

            modelBuilder.Entity("KushBot.DataClasses.Plot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastActionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Plots");
                });

            modelBuilder.Entity("KushBot.DataClasses.RarityFollow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("fk_UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RarityFollow");
                });

            modelBuilder.Entity("KushBot.DataClasses.UserEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserEvents");
                });

            modelBuilder.Entity("KushBot.DataClasses.UserPet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dupes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetType")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPets");
                });

            modelBuilder.Entity("KushBot.DataClasses.UserTutoProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserTutoProgress");
                });

            modelBuilder.Entity("KushBot.KushBotUser", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BegsMN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BegsWeekly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cheems")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedWeeklies")
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyGive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiggerState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraClaimSlots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedYoinks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FourthItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoranMaxDigMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasEgg")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastBeg")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDestroy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastNyaClaim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastTylerRage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastVendorPurchase")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastYoink")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LootedDigger")
                        .HasColumnType("TEXT");

                    b.Property<int>("LostBapsMN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LostBapsWeekly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LostBetsMN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LostBetsWeekly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LostFlipsMN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LostFlipsWeekly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LostRisksMN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LostRisksWeekly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NyaMarry")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NyaMarryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PetPity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pictures")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestIndexes")
                        .HasColumnType("TEXT");

                    b.Property<int>("RageCash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RageDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RedeemDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SecondItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedPicture")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SetDigger")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccesfulYoinks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThirdItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketMultiplier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tickets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WonBapsMN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WonBapsWeekly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WonBetsMN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WonBetsWeekly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WonDuelsMN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WonFlipChainOverFifty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WonFlipsMN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WonFlipsWeekly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WonRisksMN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WonRisksWeekly")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YikeDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Yiked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Jews");
                });

            modelBuilder.Entity("KushBot.DataClasses.Item", b =>
                {
                    b.HasOne("KushBot.KushBotUser", "Owner")
                        .WithMany("Items")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("KushBot.DataClasses.ItemPetConn", b =>
                {
                    b.HasOne("KushBot.DataClasses.Item", null)
                        .WithMany("ItemPetConns")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KushBot.DataClasses.NyaClaim", b =>
                {
                    b.HasOne("KushBot.KushBotUser", "Owner")
                        .WithMany("NyaClaims")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("KushBot.DataClasses.UserEvent", b =>
                {
                    b.HasOne("KushBot.KushBotUser", "User")
                        .WithMany("UserEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KushBot.DataClasses.UserPet", b =>
                {
                    b.HasOne("KushBot.KushBotUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KushBot.DataClasses.Item", b =>
                {
                    b.Navigation("ItemPetConns");
                });

            modelBuilder.Entity("KushBot.KushBotUser", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("NyaClaims");

                    b.Navigation("UserEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
